version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - pip install -r requirements.txt
      - pip install -r docs/requirements.txt
      - cp -r docs/assets docs/zh
      - cp -r docs/assets docs/en
      - python docs/add_docstrings.py
      - bash: |
          for dir in Tutorial/rag/notebook/chapter*/*_{videos,images}; do
            [ -e "$dir" ] || continue
            name=$(basename "$dir")
            target=$(realpath "$dir")
            ln -sfn "$target" "docs/zh/Tutorial/$name"
          done
      - python docs/ipynb2md.py
      - python docs/gen_mkdocs_yaml.py

python:
  install:
    - requirements: docs/requirements.txt

mkdocs:
  configuration: mkdocs.yml

