version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  environment:
    LAZYLLM_INIT_DOC: "True"
  jobs:
    pre_build:
      - pip install -r requirements.txt
      - pip install -r docs/requirements.txt
      - git submodule update --init --recursive --remote
      - cp -r docs/assets docs/zh
      - cp -r docs/assets docs/en
      - python docs/add_docstrings.py
      - python docs/link_assets.py
      - python docs/ipynb2md.py 2>&1 | tee -a build.log
      - python docs/gen_mkdocs_yaml.py

python:
  install:
    - requirements: docs/requirements.txt

mkdocs:
  configuration: mkdocs.yml
