version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    post_install:
      - export PYTHONPATH="$(pwd)";echo $PYTHONPATH 
      - echo $PYTHONPATH  # For debugging purposes


python:
  install:
    - requirements: docs/requirements.txt



sphinx:
  configuration: docs/source/conf.py

