version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"


python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py

commands:
  - export PYTHONPATH="${PYTHONPATH}:$(pwd)"
  - echo $PYTHONPATH  # For debugging purposes
  - sphinx-build -b html docs/source docs/build
