FROM ubuntu:22.04

WORKDIR /tmp

USER root

ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
ENV TZ=Asia/Shanghai

RUN set -ex \
    && ln -sf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone \
    && apt-get update && apt-get install -y openssh-server \
    git vim tzdata curl net-tools locales zip libtinfo5 cmake ffmpeg \
    exuberant-ctags libclang-dev tcl expect telnet rsync libibverbs1 libgl1 \
    && rm -rf /var/lib/apt/lists/* \
    && sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config \
    && service ssh start \
    && echo 'LANG="en_US.UTF-8"' > /etc/default/locale \
    && echo 'LC_ALL="en_US.UTF-8"' >> /etc/default/locale \
    && locale-gen en_US.UTF-8

RUN set -ex \
    && ARCH=$(uname -m) \
    && if [ "$ARCH" = "amd64" ] || [ "$ARCH" = "x86_64" ]; then \
         wget https://repo.anaconda.com/miniconda/Miniconda3-py310_23.1.0-1-Linux-x86_64.sh -O miniconda.sh \
         && wget https://packages.redis.io/redis-stack/redis-stack-server-7.2.0-v10.rhel7.x86_64.tar.gz -O redis.tar.gz; \
       elif [ "$ARCH" = "arm64" ] || [ "$ARCH" = "aarch64" ]; then \
         wget https://repo.anaconda.com/miniconda/Miniconda3-py310_23.1.0-1-Linux-aarch64.sh -O miniconda.sh \
         && wget https://packages.redis.io/redis-stack/redis-stack-server-7.2.0-v10.jammy.arm64.tar.gz -O redis.tar.gz; \
       else \
         echo "Unsupported architecture: $ARCH" && exit 1; \
       fi \
    && bash miniconda.sh -b -p /opt/miniconda3 \
    && rm miniconda.sh \
    && tar xf redis.tar.gz \
    && chown -R root:root /tmp && chmod 1777 /tmp \
    && mv redis-stack-server-7.2.0-v10 /usr/local/ \
    && rm redis.tar.gz

ENV PATH="/opt/miniconda3/bin:/usr/local/redis-stack-server-7.2.0-v10/bin:${PATH}"

RUN conda init bash \
    && conda create -n lazyllm --clone base \
    && echo "source activate lazyllm" > ~/.bashrc

ARG LAZYLLM_VERSION=""
ENV LAZYLLM_VERSION=$LAZYLLM_VERSION
RUN bash -c "source activate lazyllm && \
    conda install -y mpi4py && \
    pip install lazyllm==${LAZYLLM_VERSION} && \
    pip cache purge && rm -rf /tmp/*"

ENTRYPOINT ["/bin/bash"]
WORKDIR /root