name: 🐞 Bug report
description: Submit Bug feedback
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting the bug. Please fill in the following information to help us reproduce the issue.
  - type: input
    id: env
    attributes:
      label: Environment Information
      description: System version / Browser / Runtime environment
      placeholder: macOS 14.5, Chrome 118
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Reproduction Steps
      description: Write down step by step how to trigger this bug
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen ideally
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Logs
      description: Provide screenshots or logs (optional)
