# Copyright (c) 2026 LazyAGI. All rights reserved.
import json
import os
import re
from typing import Any, Dict, List, Optional, Tuple

import lazyllm

from ..base import LazyLLMGitBase
from ..checkpoint import _load_cache, _save_cache, _save_cache_multi
from ..constants import SINGLE_CALL_CONTEXT_BUDGET
from ..utils import _Progress, _safe_llm_call, JSON_OUTPUT_INSTRUCTION
from .prompt import _EXTRACT_RULES_PROMPT, _MERGE_RULES_PROMPT

_MAX_COMMENTS_PER_USER = 15
_COMMENT_COMPRESS_THRESHOLD = 150
_SPEC_MAX_RULES = 50
_SPEC_CACHE_VERSION = 3

_BOT_USER_PATTERNS = re.compile(
    r'bot$|robot$|\[bot\]|-bot-|autobot|github-actions|dependabot', re.IGNORECASE
)

_BOT_BODY_INDICATORS = re.compile(
    r'^(?:(?:this is an? )?(?:auto(?:mated|matic)?|ai)[- ](?:generated|review|suggestion|comment))'
    r'|^(?:i am (?:a |an )?(?:bot|automated|ai))'
    r'|(?:auto(?:matically)? reviewed by (?:bot|ai))'
    r'|(?:generated by (?:bot|ai|automated))',
    re.IGNORECASE | re.MULTILINE,
)

_MAINTAINER_ASSOCIATIONS = {'OWNER', 'MEMBER', 'COLLABORATOR'}

_MAINTAINER_COMPRESS_THRESHOLD = 300
_BOT_TEMPLATE_MIN_COMMENTS = 3
_BOT_TEMPLATE_MIN_PREFIX_LEN = 20
_BOT_TEMPLATE_MIN_SUFFIX_LEN = 15

_COMMENTS_CHUNK_SIZE = 8000
_MAX_MAINTAINER_COMMENTS = 20

_MERGE_CHUNK_SIZE = 40
_MERGE_CHUNK_OUTPUT = 15


def _is_merged_pr(pr: Any) -> bool:
    raw = getattr(pr, 'raw', None) or (pr if isinstance(pr, dict) else {})
    if raw.get('merged_at'):
        return True
    if raw.get('state') == 'merged':
        return True
    return False


def _strip_bot_templates(
    comments: List[Dict[str, Any]],
    templates: Dict[str, List[Tuple[str, str]]],
) -> List[Dict[str, Any]]:
    if not templates:
        return comments
    for c in comments:
        user = c.get('user', '')
        tlist = templates.get(user)
        if not tlist:
            continue
        c['is_maintainer'] = False
        body = c['body']
        for prefix, suffix in tlist:
            if (prefix and body.startswith(prefix)) or (suffix and body.endswith(suffix)):
                if prefix and body.startswith(prefix):
                    body = body[len(prefix):]
                if suffix and body.endswith(suffix):
                    body = body[:-len(suffix)]
                break
        c['body'] = body.strip()
    return [c for c in comments if c.get('body')]


def _preload_bot_templates_from_cache(  # noqa: C901
    cache_path: Optional[str], templates: Dict[str, List[Tuple[str, str]]],
) -> None:
    if not cache_path or not os.path.isfile(cache_path):
        return
    try:
        with open(cache_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
    except (json.JSONDecodeError, OSError):
        return
    for key, val in data.items():
        if not key.startswith('bot_template_'):
            continue
        user = key[len('bot_template_'):]
        try:
            t = json.loads(val) if isinstance(val, str) else val
            if isinstance(t, list) and t:
                if isinstance(t[0], list):
                    for pair in t:
                        if isinstance(pair, list) and len(pair) == 2:
                            templates.setdefault(user, []).append((pair[0], pair[1]))
                elif len(t) == 2 and isinstance(t[0], str):
                    templates.setdefault(user, []).append((t[0], t[1]))
        except (json.JSONDecodeError, TypeError):
            pass


def _accumulate_and_detect_templates(
    comments: List[Dict[str, Any]],
    templates: Dict[str, List[Tuple[str, str]]],
    cache_path: Optional[str] = None,
) -> None:
    by_user: Dict[str, List[str]] = {}
    for c in comments:
        user = c.get('user', '')
        if user:
            by_user.setdefault(user, []).append(c.get('body', ''))
    for user, bodies in by_user.items():
        if len(bodies) < _BOT_TEMPLATE_MIN_COMMENTS:
            continue
        existing = templates.get(user, [])
        if existing:
            any_hit = any(
                any((not pfx or b.startswith(pfx)) and (not sfx or b.endswith(sfx)) for b in bodies)
                for pfx, sfx in existing
            )
            if any_hit:
                continue
        prefix = os.path.commonprefix(bodies)
        nl = prefix.rfind('\n')
        if nl > 0:
            prefix = prefix[:nl + 1]
        reversed_bodies = [b[::-1] for b in bodies]
        suffix_rev = os.path.commonprefix(reversed_bodies)
        nl = suffix_rev.rfind('\n')
        if nl > 0:
            suffix_rev = suffix_rev[:nl + 1]
        suffix = suffix_rev[::-1]
        strip_prefix = prefix if len(prefix.strip()) >= _BOT_TEMPLATE_MIN_PREFIX_LEN else ''
        strip_suffix = suffix if len(suffix.strip()) >= _BOT_TEMPLATE_MIN_SUFFIX_LEN else ''
        if not strip_prefix and not strip_suffix:
            continue
        new_t = (strip_prefix, strip_suffix)
        if new_t not in existing:
            templates.setdefault(user, []).append(new_t)
            if cache_path:
                _save_cache(cache_path, f'bot_template_{user}',
                            json.dumps(templates[user]))


def _compress_comments_for_pr(llm: Any, comments: List[Dict[str, Any]]) -> str:
    indexed = [{'idx': i, 'body': c['body'], 'is_maintainer': c.get('is_maintainer', False)}
               for i, c in enumerate(comments)]
    long_items = [
        it for it in indexed
        if len(it['body']) > (_MAINTAINER_COMPRESS_THRESHOLD if it['is_maintainer'] else _COMMENT_COMPRESS_THRESHOLD)
    ]
    summaries: Dict[int, str] = {}
    if long_items:
        batch_input = [{'idx': it['idx'], 'body': it['body'][:800]} for it in long_items]
        compress_prompt = (
            'Summarize each review comment into ONE sentence (max 20 words). '
            'Preserve: (1) what is wrong and why, (2) what the reviewer PREFERS or REQUIRES as a general practice. '
            'If the comment expresses a repo-level preference (e.g. "we always use X", "please use Y instead"), '
            'preserve the preference verbatim even if it makes the summary slightly longer.\n'
            'Output a JSON array, each item: {"idx": <same>, "summary": "<one sentence>"}.\n'
            + JSON_OUTPUT_INSTRUCTION + '\n\n'
            + json.dumps(batch_input, ensure_ascii=False, indent=2)
        )
        try:
            result = _safe_llm_call(llm, compress_prompt)
            for r in (result if isinstance(result, list) else []):
                if isinstance(r, dict) and 'idx' in r and 'summary' in r:
                    summaries[int(r['idx'])] = str(r['summary'])
        except Exception as e:
            raise RuntimeError(f'Comment compression failed: {e}') from e
    lines = []
    for item in indexed:
        threshold = _MAINTAINER_COMPRESS_THRESHOLD if item['is_maintainer'] else _COMMENT_COMPRESS_THRESHOLD
        body = summaries.get(item['idx']) or item['body'][:threshold]
        user = comments[item['idx']].get('user', '')
        role = '[MAINTAINER]' if item['is_maintainer'] else '[CONTRIBUTOR]'
        lines.append(f'{role} [{user}]: {body}' if user else f'{role} {body}')
    return '\n'.join(lines)


def _truncate_comments_per_user(comments: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    by_user: Dict[str, List[int]] = {}
    for i, c in enumerate(comments):
        by_user.setdefault(c.get('user', ''), []).append(i)
    keep: set = set()
    for _user, indices in by_user.items():
        is_maint = any(comments[i].get('is_maintainer') for i in indices)
        limit = _MAX_MAINTAINER_COMMENTS if is_maint else _MAX_COMMENTS_PER_USER
        for i in indices[:limit]:
            keep.add(i)
    return [comments[i] for i in sorted(keep)]


def _extract_rules_from_pr_comments(
    llm: Any, pr_num: int, comments: List[Dict[str, Any]]
) -> List[Dict[str, Any]]:
    if not comments:
        return []
    comments = _truncate_comments_per_user(comments)
    comments_text = _compress_comments_for_pr(llm, comments)
    if len(comments_text) <= _COMMENTS_CHUNK_SIZE:
        chunks = [comments_text]
    else:
        lines = comments_text.split('\n')
        chunks, current = [], ''
        for line in lines:
            if current and len(current) + len(line) + 1 > _COMMENTS_CHUNK_SIZE:
                chunks.append(current)
                current = line
            else:
                current = current + '\n' + line if current else line
        if current:
            chunks.append(current)
    all_rules: List[Dict[str, Any]] = []
    for chunk in chunks:
        prompt = _EXTRACT_RULES_PROMPT.replace('{pr_num}', str(pr_num)).replace('{{comments_text}}', chunk)
        try:
            result = _safe_llm_call(llm, prompt)
            all_rules.extend(r for r in (result if isinstance(result, list) else []) if isinstance(r, dict))
        except Exception as e:
            raise RuntimeError(f'Rule extraction for PR #{pr_num} failed: {e}') from e
    return all_rules


def _normalize_title(title: str) -> str:
    return re.sub(r'[^a-z0-9 ]', '', title.lower()).strip()


def _deterministic_pre_dedup(rules: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    groups: Dict[str, List[Dict[str, Any]]] = {}
    for r in rules:
        key = (_normalize_title(r.get('title', '')), r.get('category', 'other'))
        groups.setdefault(str(key), []).append(r)
    deduped = []
    for group in groups.values():
        base = dict(group[0])
        base['source_count'] = base.get('source_count', 0) or len(group)
        all_detect = []
        for r in group:
            all_detect.extend(r.get('detect') or [])
        base['detect'] = list(dict.fromkeys(all_detect))[:10]
        for field in ('bad_example', 'good_example', 'rationale'):
            longest = max((r.get(field) or '' for r in group), key=len, default='')
            if longest:
                base[field] = longest
        deduped.append(base)
    return deduped


def _llm_merge_chunk(llm: Any, chunk: List[Dict[str, Any]], max_output: int) -> List[Dict[str, Any]]:
    rules_json = json.dumps(chunk, ensure_ascii=False, indent=2)
    budget = max(8000, SINGLE_CALL_CONTEXT_BUDGET - 6000)
    if len(rules_json) > budget:
        rules_json = rules_json[:budget]
    try:
        result = _safe_llm_call(llm, _MERGE_RULES_PROMPT.format(
            rules_json=rules_json, max_rules=max_output))
        return [r for r in (result if isinstance(result, list) else []) if isinstance(r, dict)]
    except Exception as e:
        lazyllm.LOG.warning(f'Chunk merge failed: {e}')
        return chunk[:max_output]


def _merge_rule_cards(llm: Any, all_rules: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    if not all_rules:
        return []
    deduped = _deterministic_pre_dedup(all_rules)
    if len(deduped) <= _MERGE_CHUNK_SIZE:
        return _llm_merge_chunk(llm, deduped, _SPEC_MAX_RULES)
    by_cat: Dict[str, List[Dict[str, Any]]] = {}
    for r in deduped:
        by_cat.setdefault(r.get('category', 'other'), []).append(r)
    chunks: List[List[Dict[str, Any]]] = []
    current_chunk: List[Dict[str, Any]] = []
    for cat_rules in by_cat.values():
        cat_rules.sort(key=lambda r: {'P0': 0, 'P1': 1}.get(r.get('severity', 'P2'), 2))
        for r in cat_rules:
            current_chunk.append(r)
            if len(current_chunk) >= _MERGE_CHUNK_SIZE:
                chunks.append(current_chunk)
                current_chunk = []
    if current_chunk:
        chunks.append(current_chunk)
    intermediate: List[Dict[str, Any]] = []
    for chunk in chunks:
        intermediate.extend(_llm_merge_chunk(llm, chunk, _MERGE_CHUNK_OUTPUT))
    if len(intermediate) <= _SPEC_MAX_RULES:
        return intermediate
    return _llm_merge_chunk(llm, intermediate, _SPEC_MAX_RULES)


def _get_attr(obj: Any, attr: str) -> str:
    return (obj.get(attr) if isinstance(obj, dict) else getattr(obj, attr, '')) or ''


def _fetch_all_pr_comments(backend: LazyLLMGitBase, pr_num: int) -> List[Dict[str, Any]]:  # noqa: C901
    comments: List[Dict[str, Any]] = []
    try:
        res = backend.list_review_comments(pr_num)
        if res.get('success'):
            for c in (res.get('comments') or []):
                body = _get_attr(c, 'body').strip()
                user = _get_attr(c, 'user')
                if not body:
                    continue
                raw = (c.get('raw') if isinstance(c, dict) else getattr(c, 'raw', {})) or {}
                assoc = (raw.get('author_association') or '').upper()
                is_bot = bool(_BOT_USER_PATTERNS.search(user)) or bool(_BOT_BODY_INDICATORS.search(body))
                is_maint = assoc in _MAINTAINER_ASSOCIATIONS and not is_bot
                cid = c.get('id') if isinstance(c, dict) else getattr(c, 'id', None)
                comments.append({
                    'user': user, 'body': body, 'is_maintainer': is_maint,
                    'is_bot': is_bot, 'id': cid, 'raw': raw,
                })
    except Exception as e:
        lazyllm.LOG.warning(f'PR #{pr_num} review comments fetch error: {e}')
    try:
        res2 = backend.list_issue_comments(pr_num)
        if res2.get('success'):
            for c in (res2.get('comments') or []):
                body = (c.get('body') or '').strip()
                user = (c.get('user') or '').strip()
                if not body:
                    continue
                raw = (c if isinstance(c, dict) else {})
                assoc = (raw.get('author_association') or '').upper()
                is_bot = bool(_BOT_USER_PATTERNS.search(user)) or bool(_BOT_BODY_INDICATORS.search(body))
                is_maint = assoc in _MAINTAINER_ASSOCIATIONS and not is_bot
                cid = c.get('id') if isinstance(c, dict) else getattr(c, 'id', None)
                comments.append({
                    'user': user, 'body': body, 'is_maintainer': is_maint,
                    'is_bot': is_bot, 'id': cid, 'raw': raw,
                })
    except Exception as e:
        lazyllm.LOG.warning(f'PR #{pr_num} issue comments fetch error: {e}')
    return comments


def _collect_rules_for_pr(
    backend: LazyLLMGitBase, llm: Any, pr: Any,
    idx: int, total: int, cache_path: Optional[str],
    prog: Any, all_rules: List[Dict[str, Any]],
    bot_templates: Optional[Dict[str, List[Tuple[str, str]]]] = None,
) -> None:
    pr_num = getattr(pr, 'number', None) or (pr.get('number') if isinstance(pr, dict) else None)
    if pr_num is None:
        prog.update(f'[{idx}/{total}] skipped (no number)')
        return
    pr_cache_key = f'spec_pr_{pr_num}_v{_SPEC_CACHE_VERSION}_rules'
    cached_rules_str = _load_cache(cache_path, pr_cache_key)
    if cached_rules_str:
        try:
            rules = json.loads(cached_rules_str)
            all_rules.extend(rules)
            prog.update(f'[{idx}/{total}] PR #{pr_num} — {len(rules)} rules (cached)')
            return
        except (json.JSONDecodeError, TypeError):
            pass
    comments = _fetch_all_pr_comments(backend, pr_num)
    if not comments:
        prog.update(f'[{idx}/{total}] PR #{pr_num} — 0 human comments → skipped')
        return
    if bot_templates:
        comments = _strip_bot_templates(comments, bot_templates)
    if not comments:
        prog.update(f'[{idx}/{total}] PR #{pr_num} — 0 comments after template strip → skipped')
        return
    rules = _extract_rules_from_pr_comments(llm, pr_num, comments)
    if rules:
        _save_cache(cache_path, pr_cache_key, json.dumps(rules, ensure_ascii=False))
    all_rules.extend(rules)
    prog.update(f'[{idx}/{total}] PR #{pr_num} — {len(comments)} comments → {len(rules)} rules extracted')


def analyze_historical_reviews(  # noqa: C901
    backend: LazyLLMGitBase, llm: Any, cache_path: Optional[str] = None, max_prs: int = 200
) -> str:
    cached = _load_cache(cache_path, 'review_spec')
    cached_max_prs_str = _load_cache(cache_path, 'review_spec_max_prs')
    cached_max_prs = int(cached_max_prs_str) if cached_max_prs_str and cached_max_prs_str.isdigit() else 0
    cached_ver_str = _load_cache(cache_path, 'spec_cache_version')
    cached_ver = int(cached_ver_str) if cached_ver_str and cached_ver_str.isdigit() else 0
    if cached and not cached.startswith('(') and cached_max_prs >= max_prs and cached_ver >= _SPEC_CACHE_VERSION:
        return cached

    merged: List[Any] = []
    fetch_size = max_prs
    while len(merged) < max_prs:
        pr_list_res = backend.list_pull_requests(state='closed', max_results=fetch_size)
        if not pr_list_res.get('success'):
            return '(historical review analysis unavailable)'
        prs = pr_list_res.get('list') or []
        if not prs:
            break
        merged = [p for p in prs if _is_merged_pr(p)]
        if len(merged) >= max_prs or len(prs) < fetch_size:
            break
        fetch_size = min(fetch_size * 2, 1000)
    target = merged[:max_prs]
    total = len(target)

    _empty = '(no historical review comments found)'
    if not target:
        _save_cache_multi(cache_path, {
            'review_spec': _empty, 'review_spec_max_prs': str(max_prs),
            'spec_cache_version': str(_SPEC_CACHE_VERSION),
        })
        return _empty

    prog = _Progress('Spec: extracting rules from historical PRs', total)
    all_rules: List[Dict[str, Any]] = []
    bot_templates: Dict[str, List[Tuple[str, str]]] = {}
    _preload_bot_templates_from_cache(cache_path, bot_templates)
    for idx, pr in enumerate(target, 1):
        pr_num = getattr(pr, 'number', None) or (pr.get('number') if isinstance(pr, dict) else None)
        if pr_num is None:
            prog.update(f'[{idx}/{total}] skipped (no number)')
            continue
        pr_cache_key = f'spec_pr_{pr_num}_v{_SPEC_CACHE_VERSION}_rules'
        cached_rules_str = _load_cache(cache_path, pr_cache_key)
        if cached_rules_str:
            try:
                rules = json.loads(cached_rules_str)
                all_rules.extend(rules)
                prog.update(f'[{idx}/{total}] PR #{pr_num} — {len(rules)} rules (cached)')
                continue
            except (json.JSONDecodeError, TypeError):
                pass
        comments = _fetch_all_pr_comments(backend, pr_num)
        if not comments:
            prog.update(f'[{idx}/{total}] PR #{pr_num} — 0 comments → skipped')
            continue
        _accumulate_and_detect_templates(comments, bot_templates, cache_path)
        human_comments = [c for c in comments if not c.get('is_bot')]
        human_comments = _strip_bot_templates(human_comments, bot_templates)
        if not human_comments:
            prog.update(f'[{idx}/{total}] PR #{pr_num} — 0 human comments after filtering → skipped')
            continue
        rules = _extract_rules_from_pr_comments(llm, pr_num, human_comments)
        if rules:
            _save_cache(cache_path, pr_cache_key, json.dumps(rules, ensure_ascii=False))
        all_rules.extend(rules)
        prog.update(f'[{idx}/{total}] PR #{pr_num} — {len(comments)} comments → {len(rules)} rules extracted')
    prog.done(f'{len(all_rules)} raw rules from {total} PRs, merging...')

    if not all_rules:
        _save_cache_multi(cache_path, {
            'review_spec': _empty, 'review_spec_max_prs': str(max_prs),
            'spec_cache_version': str(_SPEC_CACHE_VERSION),
        })
        return _empty

    merged_rules = _merge_rule_cards(llm, all_rules)
    categories: Dict[str, List[Dict[str, Any]]] = {}
    for r in merged_rules:
        cat = r.get('category', 'other')
        categories.setdefault(cat, []).append(r)
    summaries = [
        {'rule_id': r.get('rule_id', ''), 'title': r.get('title', ''), 'category': r.get('category', 'other')}
        for r in merged_rules
    ]
    details = {r.get('rule_id', f'R{i:03d}'): r for i, r in enumerate(merged_rules)}
    repo_wide = [r for r in merged_rules if r.get('scope') == 'repo_wide']
    preferences, mandatory, forbidden = [], [], []
    for r in repo_wide:
        entry = {
            'norm': r.get('title', ''),
            'rationale': r.get('rationale', ''),
            'source_count': r.get('source_count', 1),
            'rule_id': r.get('rule_id', ''),
        }
        fix = (r.get('fix') or '').lower()
        title = (r.get('title') or '').lower()
        if any(kw in title or kw in fix for kw in ('must', 'require', 'always', 'mandatory')):
            mandatory.append(entry)
        elif any(kw in title or kw in fix for kw in ('never', 'forbid', 'prohibit', 'do not', 'disallow')):
            forbidden.append(entry)
        else:
            preferences.append(entry)
    repo_norms = {'preferences': preferences, 'mandatory': mandatory, 'forbidden': forbidden}
    review_spec = json.dumps(
        {'summaries': summaries, 'categories': categories, 'details': details, 'repo_norms': repo_norms},
        ensure_ascii=False,
    ) or '(review spec analysis unavailable)'
    _save_cache_multi(cache_path, {
        'review_spec': review_spec, 'review_spec_max_prs': str(max_prs),
        'spec_cache_version': str(_SPEC_CACHE_VERSION),
    })
    return review_spec
