'''CLI tool: merge dev_* migration files into a single release file.

Usage (from repo root):
    python -m lazyllm.tools.rag.db_migrate merge --name v110_my_feature
    python -m lazyllm.tools.rag.db_migrate merge --name v110_my_feature --db sqlite:///path.db
'''
from __future__ import annotations

import argparse
import ast
import os
import re
import textwrap
from datetime import datetime

from lazyllm import LOG

_VERSIONS_DIR = os.path.join(os.path.dirname(__file__), 'versions')
_MIGRATIONS_TABLE = 'lazyllm_schema_migrations'


def _dev_files():
    files = []
    for fname in sorted(os.listdir(_VERSIONS_DIR)):
        if fname.startswith('dev_') and fname.endswith('.py'):
            files.append(fname)
    return files


def _next_release_number():
    numbers = []
    for fname in os.listdir(_VERSIONS_DIR):
        m = re.match(r'^(\d{4})_', fname)
        if m:
            numbers.append(int(m.group(1)))
    return max(numbers, default=0) + 1


def _extract_up_body(filepath: str) -> str:
    with open(filepath) as f:
        source = f.read()
    tree = ast.parse(source)
    for node in ast.walk(tree):
        if isinstance(node, ast.FunctionDef) and node.name == 'up':
            lines = source.splitlines(keepends=True)
            # skip the def line itself; dedent the body
            body_lines = lines[node.body[0].lineno - 1: node.end_lineno]
            return textwrap.dedent(''.join(body_lines))
    return ''


def _dev_version_key(fname: str):
    m = re.match(r'^(dev_\d+)_', fname)
    return m.group(1) if m else fname


def merge(name: str, db_url: str | None = None):
    devs = _dev_files()
    if not devs:
        LOG.info('No dev_* files found — nothing to merge.')
        return

    release_no = _next_release_number()
    release_filename = f'{release_no:04d}_{name}.py'
    release_path = os.path.join(_VERSIONS_DIR, release_filename)
    release_version = f'{release_no:04d}'

    combined_bodies = []
    dev_versions = []
    for fname in devs:
        fpath = os.path.join(_VERSIONS_DIR, fname)
        body = _extract_up_body(fpath)
        if body.strip():
            combined_bodies.append(f'    # --- from {fname} ---')
            for line in body.splitlines():
                combined_bodies.append(f'    {line}' if line.strip() else '')
        dev_versions.append(_dev_version_key(fname))

    merged_body = '\n'.join(combined_bodies)

    content = (
        f"'''Merged release migration: {name}\n\n"
        f"Auto-generated by db_migrate merge on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
        f"Source dev files: {', '.join(devs)}\n'''\n"
        'from __future__ import annotations\n\n'
        'import sqlalchemy\n'
        'from sqlalchemy import text\n'
        'from lazyllm import LOG\n\n\n'
        'def up(engine) -> None:\n'
        f'{merged_body}\n'
    )

    with open(release_path, 'w') as f:
        f.write(content)
    LOG.info(f'Created: {release_filename}')

    for fname in devs:
        os.remove(os.path.join(_VERSIONS_DIR, fname))
        LOG.info(f'Removed: {fname}')

    if db_url:
        _update_db_records(db_url, dev_versions, release_version, name)

    LOG.info(f'Merge complete → {release_filename}')


def _update_db_records(db_url: str, dev_versions: list, release_version: str, name: str):
    try:
        from sqlalchemy import create_engine, text as _text
        from .runner import _insert_ignore_sql
        engine = create_engine(db_url)
        insert_sql = _insert_ignore_sql(
            engine, _MIGRATIONS_TABLE, ('version', 'name', 'applied_at')
        )
        with engine.connect() as conn:
            for dv in dev_versions:
                conn.execute(
                    _text(f'DELETE FROM {_MIGRATIONS_TABLE} WHERE version = :v'),
                    {'v': dv},
                )
            conn.execute(
                _text(insert_sql),
                {
                    'version': release_version,
                    'name': f'{release_version}_{name}',
                    'applied_at': datetime.now(),
                },
            )
            conn.commit()
        LOG.info(f'Updated DB: replaced {dev_versions} → {release_version}')
    except Exception as exc:
        LOG.warning(f'Could not update migration records in DB: {exc}')


def main():
    parser = argparse.ArgumentParser(description='Merge dev_* migration files into a release file')
    parser.add_argument('action', choices=['merge'], help='Action to perform')
    parser.add_argument('--name', required=True, help='Release name suffix (e.g. v110_my_feature)')
    parser.add_argument('--db', default=None, help='SQLAlchemy DB URL to update migration records')
    args = parser.parse_args()
    if args.action == 'merge':
        merge(args.name, args.db)


if __name__ == '__main__':
    main()
