name: Deploy Documentation

on:
  push:
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: tps_sco_nv
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract tag
        id: extract_tag
        run: |
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV

      - name: Build documentation
        run: |
          set -e
          export PYTHONPATH="${PYTHONPATH}:$(pwd)"
          cd docs
          make clean
          make html
          cd ..
          if [ -d "docs/build" ]; then
            mv docs/build /home/mnt/platform_ci/GitHub/LazyAGI/LazyLLM_doc/$BRANCH_NAME
          else
            echo "Build directory does not exist."
            exit 1
          fi
