name: Lint And Build Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.9'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install flake8

      - name: Run flake8
        run: |
          source venv/bin/activate
          flake8 .

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.9'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY_VERSION }}

      - name: Install deps
        shell: bash
        run: |
          set -ex
          cp LazyLLM-Env/poetry.lock . 
          export POETRY_CACHE_DIR=$(mktemp -d)
          poetry install
          rm -rf $POETRY_CACHE_DIR

      - name: Build
        shell: bash
        run: poetry build

      - name: Test installing built package
        shell: bash
        run: python -m pip install .

      - name: Test import
        shell: bash
        working-directory: /tmp
        run: python -c "import lazyllm"

  Check_requirements:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.9'

      - name: Check requirements
        shell: bash
        run: |
          pip install toml
          python scripts/check_requirements.py
