name: Lint Python Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.9'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install flake8

      - name: Run flake8
        run: |
          source venv/bin/activate
          flake8 .