name: TEST - RAG

on:
  push:
    branches:
      - yzh/fix_paddleocr
  workflow_dispatch:

jobs:
  rag_test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    defaults:
      run:
        shell: bash
    env:
      PYTHON_VERSION: "3.10"
      LAZYLLM_DEFAULT_LAUNCHER: "empty"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Install test requirements
        run: |
          pip install -r tests/requirements.txt
          pip install -r tests/requirements_linux.txt

      - name: Run RAG tests
        run: |
          python -m pytest -v --tb=line --order-scope=class \
            -m "not skip_on_linux" tests/basic_tests/RAG \
            --ignore=tests/basic_tests/RAG/test_store.py \
            --ignore=tests/basic_tests/RAG/test_reader.py
